### ISSUE TITLE
Doesnt Works

### ISSUE THREAD

**Issue by BrayantVideos1** [svtcore/rlgarage-trade-bump#1]
It doesnt bump the trades

**Comment by svtcore** [comment]
Hi, due changes in the site UI some tags were remove. It called error, already fixed it. Uninstall old version of extension and install new according steps in [README.md](https://github.com/svtcore/rlgarage-trade-bump/blob/main/README.md)

**Comment by BrayantVideos1** [comment]
i did it like that, but it doesnt work.

**Comment by BrayantVideos1** [comment]
Worked, TYSM.

**Comment by BrayantVideos1** [comment]
But now when i activate it after the 2nd bump wave, it get bugged and i get bump cooldown.

**Comment by svtcore** [comment]
Just checked 5 times in row, works correctly. Basic logs available in chrome console

**Comment by BrayantVideos1** [comment]
ok, ty let me see what happens so. Tysm for the fast answer.

**Comment by BrayantVideos1** [comment]
This is the problem: if u have 15 trades and 5 of them are already bumped, the extension try to bump it anyways, so if some user is reading this, make sure all the trades you ve selected are ready for being bumped else you will get one hour of bump cooldown.

**Comment by svtcore** [comment]
> This is the problem: if u have trades and like 5 of them are already bumped, the extension try to bump it anyways, so if some user is reading this, make sure all the trades you ve selected are ready for being bumped else you will get one hour of bump cooldown.

Currently extension doesn't check if offer has bumped, it just bump all selected trades when timer is expired (15 minutes). Maybe in the next update will be implemented bump check
